services:
  - type: web
    name: backend
    env: docker
    dockerContext: .
    dockerfilePath: server/Dockerfile
    startCommand: npm run start:all
    envVars:
      - key: PORT
        value: 3000
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: MONGO_URI
        sync: false  # Externally set environment variable in Render dashboard

  - type: redis
    name: redis
    plan: free
