services:
  - type: web
    name: backend
    env: docker
    dockerContext: .
    dockerfilePath: server/Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: REDIS_HOST
        value: redis
      - key: REDIS_PORT
        value: 6379
      - key: MONGO_URI
        sync: false  # Externally set environment variable in Render dashboard

  - type: redis
    name: redis
    plan: free
    ipAllowList: []  # Restrict access to only Render services (backend)
